### ISSUE TITLE
miniwfa on syntenic regions

### ISSUE THREAD

**Issue by diego-rt** [lh3/miniwfa#2]
Hi,

I would like to use miniwfa heuristic mode to align a 3 Mbp region from the Axolotl genome to its 200 kbp syntenic region in the human genome, with a particular emphasis on aligning any common repetitive regions as best as possible. 

I was wondering whether you could give me your feedback as to whether this is the most suitable WFA implementation to achieve this with reasonable time and memory requirements? I have several thousands of such sequence pairs, which makes these requirements problematic. 

In addition, am I correct in assuming that the `test-mwf -c` output is in paf format? Any advice on how to convert this format to fasta .aln or sam formats for further processing of the alignment? 

Thanks in advance!

**Comment by lh3** [comment]
miniwfa may not be the best choice for your application. You may consider traditional genome alignment tools like LASTZ etc. I guess they will work better.
